baseURL = "https://xiaozhu.dev/"
title = "å°çŒª"
theme = "hugo-notepadium"
copyright = " & Leo"

languageCode = "zh-cn"
hasCJKLanguage = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = "XXX"

# Google Analytics
googleAnalytics = "UA-165555892-1"

[markup.highlight]
codeFences = true
noClasses = false

[markup.goldmark.renderer]
unsafe = true  # enable raw HTML in Markdown

[params]
style = "auto"  # default: auto. light: light theme, dark: dark theme, auto: based on system.
dateFormat = "Monday, January 2, 2006"  # if unset, default is "2006-01-02"
logo = "./xiaozhu_logo.png"  # if you have a logo png
slogan = "ã€Œå·±æ‰€ä¸æ¬² ğŸ™ å‹¿æ–½äºäººã€"
author = "å°çŒª"
description = "Javascriptï¼Œå‰ç«¯ï¼Œç¼–ç¨‹ï¼Œå°çŒªï¼Œæœ‰è¶£çš„çµé­‚ï¼Œç§‘æŠ€ï¼Œäººæ–‡ï¼Œæƒ³æ³•ï¼Œéšç¬”ï¼Œæ€è€ƒï¼Œæ„Ÿå¹ï¼Œç¬é—´ï¼Œç¬”è®°..."
license = "ç‰ˆæƒç”³æ˜ï¼šè½¬è½½è¯·æ³¨æ˜æ¥æºä¸”é™„ä¸Šé“¾æ¥"  # CC License
fullRss = false # Puts entire HTML post into rss 'description' tag. If unset, default is false.
cover = "https://cdn.jsdelivr.net/gh/mopig/oss@master/uPic/202005/THe5ip.jpg"

[params.comments]
enable = true  # En/Disable comments globally, default: false. You can always enable comments on per page.

[params.math]
enable = false  # optional: true, false. Enable globally, default: false. You can always enable math on per page.
use = "katex"  # option: "katex", "mathjax". default: "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "xcode"
darkTheme = "xcode-dark"  # apply this theme in dark mode

[params.share]
enable = false
addThisId = "ra-5eb047212ecfe30b"
inlineToolId = ""

[params.nav]
showCategories = true       # /categories/
showTags = true             # /tags/

# custom navigation items
[[params.nav.custom]]
title = "æ”¶è—"
url = "/links"

[[params.nav.custom]]
title = "å…³äº"
url = "/about"

# [[params.nav.custom]]
# title = "Github"
# url = "https://github.com/mopig"

# Display author profile at article bottom

[params.profile]
  enable = true
  name = "Leo"
  bio = "*Love & Peace*"  # support markdown syntax
  twitter = "leoaee"  # https://twitter.com/XXX
  github = "mopig"  # https://github.com/XXX
#  docker = "mopig"  # https://hub.docker.com/u/XXX
  email = "leoaee@gmail.com"  # mailto:XXX@mail.com

[taxonomies]
  category = "categories"
  tag = "tags"